### ISSUE TITLE
Закончить стилизацию сайта

### ISSUE THREAD

**Issue by brusselboy** [torin-asakura/shinny-dvor#10]
## Header

- [x] Ссылки в header должны быть жирнее
- [x] Доделать кнопку выбора радиуса
- [x] У навигации нету подсветки ссылки

## Hero

- [x] Доделать scrollspy (не прокручивает до следующего блока)
- [x] Доделать стилизацию ссылок социальных сетей

## Services 

- [x] Нету плитки выбора радиуса

## Slider

- [x] Не сделан

## Footer

- [x] У ссылок не правильный цвет
- [x] Не хватает текста с адресом и телефоном

## Sign up

- [x] Не правильный font-weight
- [x] Инпуты не соответствуют дизайну
- [x] Нету валидации кнопки Записаться

## Services page

- [x] Нету аддона, который указывается около цены серым цветом

## Contact page

- [x] Нету списка информации о точке (адрес)

**Comment by brusselboy** [comment]
## Валидация в Sign up
### Описание проблемы:
Не учитываются состояния нескольких радио кнопок. Это должно выглядеть следующим образом:

1. Пользователь выбирает радиус
2. Выбирает кузов
3. Выбирает тип ремонта

Сейчас же это работает только если выбрать тип ремонта и нажать любую радио-кнопку

Происходит это из-за того, что отрисовываются два одинаковых компонента [radio1](https://github.com/torin-asakura/shinny-dvor/blob/feat/finalize-styles/site/booking-page/src/booking/booking.component.tsx#L46) [radio2](https://github.com/torin-asakura/shinny-dvor/blob/feat/finalize-styles/site/booking-page/src/booking/booking.component.tsx#L52). 
@TFK70 как мне сделать, чтобы при выборе допустим радиуса, не было никакого эффекта у радио кнопок выбора кузова?  

https://user-images.githubusercontent.com/35490768/157824865-a2ddaf13-1fc4-41f7-adb0-9aceed89d38c.mp4

**Comment by TFK70** [comment]
@brusselboy ну а что ты еще ожидал когда ты так делаешь? https://github.com/torin-asakura/shinny-dvor/blob/feat/finalize-styles/site/booking-page/src/booking/radio-list/radio-list.component.tsx#L5

Подумай

**Comment by brusselboy** [comment]
## Баг с селектом

Валидация работает, но когда в селекте хочешь перевыбрать айтем, он сбрасывает состояние на false, даже если нажать на тот же самый, который выбран

Компонент [Select](https://github.com/torin-asakura/shinny-dvor/blob/feat/finalize-styles/ui/select/src/select.component.tsx)
[Тут](https://github.com/torin-asakura/shinny-dvor/blob/feat/finalize-styles/site/booking-page/src/booking/booking.component.tsx#L58) отрисовывается. 
Пока даже представления не имею куда копать, в чём может быть проблема?


https://user-images.githubusercontent.com/35490768/157838550-35d60284-a4d0-401d-a224-eafcb3673e8c.mp4

**Comment by TFK70** [comment]
@brusselboy для того чтобы у ссылки появлялось состояние active тебе необходимо использовать NavLink. Сейчас на проекте старая версия `@atls-ui-parts/link`, так что тебе нужно реинитнуть `@ui/link` использовав последнюю версию `@atls-ui-parts/link`

Пример инициализации линка можно посмотреть и запустить [тут](https://github.com/atls/uikit/blob/master/ui-proto/link/src/link.stories.tsx)

**Comment by TFK70** [comment]
### Слайдер

Для слайдера будет использоваться либа [framer-motion](https://www.framer.com/docs/)

### Требования

- [ ] Само собой, должен быть реализован механизм плавного переключения слайдов
- [ ] Переключение слайдов должно осуществляться с помощью [стрелок](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=315%3A176)
- [ ] Количество слайдов и активный слайд должны отображаться в [дот-меню внизу](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=315%3A176)
- [ ] Размер у [активного слайда](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=315%3A147) должен быть чуть больше обычного
- [ ] У каждого слайда внизу должна отображаться [доп. информация](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=315%3A155). При переключении слайда блок должен исчезать с анимацией fade-out и появляться с анимацией fade-in (дам инструкции как это можно сделать, механизм уже написан)

**Comment by brusselboy** [comment]
## Ошибка при нажатии на ссылку
@TFK70 
Что сделал:

1. Обновил [@atls-ui-parts/link](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/a3f56603d15beec05134256d37be97d28c5d020c#diff-923e3c4d228ab96c5e730317866e0d92d67039b405b6a9ba2fb53f26c1dff26aR22-R25)
2. [Заменил](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/a3f56603d15beec05134256d37be97d28c5d020c#diff-b8c88be1e3c44a0dd1fff0c7712f8d3c57f1fefd60d071308769aae556555f58R57) старый NextLink на новый [Link](https://github.com/torin-asakura/shinny-dvor/pull/11/files#diff-989940038ae2c23a8cfa00912bc7925d964039cb26d07cbcaf69756d351752ce)

Теперь при нажатии на любую ссылку & кнопку появляется такая ошибка
![Снимок экрана от 2022-03-15 19-53-33](https://user-images.githubusercontent.com/35490768/158418324-2b70ddae-483b-4c36-9367-1bbc2391ff1d.png)

Скорее всего я не понимаю фундаментального, как должен работать компонент Link, [пример](https://github.com/atls/uikit/blob/master/ui-proto/link/src/link.stories.tsx) смотрел, не понимаю как это работает

**Comment by brusselboy** [comment]
@TFK70 [commit](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/fd3935987f9b846f0cc29422054fb84cf6381ce6) исправил зависимости с next и поменял href на path, всё равно выдает ту же самую ошибку 
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'auth')

В чём может быть проблема?

**Comment by brusselboy** [comment]
@TFK70 Заменил в компонентах с навигацией href на path, ошибка не появляется, но по ссылке не переходит. [commit](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/dd59802533875c621e59ae8b56a76a6dfc8cf248) с замененными href. Вопрос "В чём может быть проблема?" актуален

**Comment by TFK70** [comment]
> @TFK70 [commit](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/fd3935987f9b846f0cc29422054fb84cf6381ce6) исправил зависимости с next и поменял href на path, всё равно выдает ту же самую ошибку Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'auth')
> 
> В чём может быть проблема?

Из коммита ошибка не воспроизводится - у меня на клик по ссылке в навигейшене просто ничего не происходит.

Это, в свою очередь, происходит потому что ты используешь Link, а не NextLink или NextNavLink. Если ты внимательнее почитаешь то, что ты написал в `@ui/link` - увидишь, что Link это обычный тег `<a>`, а у него в свою очередь остается `href`, а не `path`

**Comment by brusselboy** [comment]
## Не отрисовывается Divider
[commit](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/d001c514436fdfc3fd31300b50280cf23ef105be)

> @brusselboy для того чтобы у ссылки появлялось состояние active тебе необходимо использовать NavLink. Сейчас на проекте старая версия `@atls-ui-parts/link`, так что тебе нужно реинитнуть `@ui/link` использовав последнюю версию `@atls-ui-parts/link`

Заменил в компоненте [NavigationList](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/d001c514436fdfc3fd31300b50280cf23ef105be#diff-5ea3e602c478f42ddae86d76885426a35c9b08693978d1777c713870f8b978b1R11-R19) NextLink на NextNavLink, но состояние не сохраняется.

Также сам [divider](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/d001c514436fdfc3fd31300b50280cf23ef105be#diff-e1b87bbd26b7b7fe185e14480645a5519b520c9f4d441b40aca5b55fc09aaf3dR29) не отрисовывается, отрисовываться он должен если в [стейте](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/d001c514436fdfc3fd31300b50280cf23ef105be#diff-e1b87bbd26b7b7fe185e14480645a5519b520c9f4d441b40aca5b55fc09aaf3dR15) pressed имеет значение true, есть [console.log](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/d001c514436fdfc3fd31300b50280cf23ef105be#diff-e1b87bbd26b7b7fe185e14480645a5519b520c9f4d441b40aca5b55fc09aaf3dR16), по нему можно увидеть, что при нажатии на ссылку приходит true потом сразу же приходит false, я полагаю что это из-за обновления страницы. В чем может быть проблема? не правильно использую NextNavLink?

**Comment by TFK70** [comment]
[Реф](https://github.com/torin-asakura/shinny-dvor/issues/10#issuecomment-1066768903)

## Онбординг

### Вводные

Для реализации слайдера будет использоваться библиотека [splide](https://splidejs.com)

### Подводные камни

splide довольно некомфортно использовать на нашем стеке, даже при наличии [адаптера под реакт](https://splidejs.com/integration/react-splide/). Основная проблема заключается в импорте стилей: они лежат в бандле либы в виде css файлов, так что их придется импортить "as-it".

Соответственно, раз уж нам приходится отдельно импортировать css для сплайда - для управления его компонентами мы будем присваивать компонентам соответствующие `className`, которые описаны в доке.

В сплайде так же уже есть встроенные контролсы: стрелочки для прокручивания и dot-nav. Но, их стили нам не подходят, так что по [аналогии](https://splidejs.com/guides/arrows/#custom-arrows) нужно вставлять свои кастомные компоненты.

### Текущее состояние

Инициализирован [каркас слайдера](https://github.com/torin-asakura/shinny-dvor/tree/feat/finalize-styles/ui/slider/src). Его основная задача - разбить слайдер на отдельные компоненты, с которыми нам предстоит работать более "близко". Помимо этого в приложении уже были заимпорчены стили сплайда в `_app` и сам слайдер уже [маунтился](https://github.com/torin-asakura/shinny-dvor/blob/feat/finalize-styles/site/works-examples-fragment/src/works-examples.component.tsx#L14) во фрагменте.

### TODO

- [ ] Стилизовать dot-nav
- [ ] Стилизовать стрелки
- [ ] Стилизовать активный слайд
- [ ] Стилизовать неактивные слайды (у них спрятана доп. информация о слайде)
- [ ] Адаптировать под мобилки

**Comment by brusselboy** [comment]
## Баги у слайдера
@TFK70 
Проблема в верстке. 
Основные [изменения](https://github.com/torin-asakura/shinny-dvor/pull/11/commits/0351da42779d5ec76aa990a7e1a0f0b2df3447fa#diff-2e34b6bb89dac75f0474114068d08ca220a3c47df99f2d3ed43d9181bc96a8baR24-R34) в вертске, из-за которых и происходят эти проблемы. 
1. Элементы не центруются по центру (видно вначале видео). Если нажать слайдер, тогда элементы становятся по центру. Я так и не разобрался с чем это связано
2. При скролле элементов слайдера происходят необъяснимые вещи с изменением ширины&высоты элементов

https://user-images.githubusercontent.com/35490768/161079082-ebd260de-a007-45bf-b18c-72fb4bad2294.mp4

**Comment by TFK70** [comment]
@brusselboy нужно дебажить. Здесь 2 варианта: либо либа работает криво, либо ты ее неправильно используешь

1. Сначала, разумеется, проверим что либа корректно работает в твоем окружении на простых кейсах. В этом случае самые разумный вариант - воспроизвести пример слайдера из документации: добавить такие же стили и все такое. Если пример из документации воспроизведенный в твоем окружении работает корректно - смотри 2 пункт. Если нет - продолжай дебажить: либо ищи что ты забыл добавить пока делал слайдер, либо смотри на окружение (стили, как правило). Так же не забывай гуглить какие-то кейсы, вполне возможно их уже за тебя когда-то решали
2. Если ты удостоверился что либа работает корректно - начинай **пошагово** трансформировать пример из либы в то, что должно у тебя быть в конечном итоге. Пошаговость важна, т.к. в таком случае ты сможешь максимально точно локализовать проблему, из-за которой у тебя все ломается - там уже можешь начинать гуглить, играться, обращаться за помощью после 30 мин

**Comment by TFK70** [comment]
> не понимаю как определять активный это слайд или нет

А как ты тогда меняешь размер у активного слайда?

**Comment by TFK70** [comment]
> > А как ты тогда меняешь размер у активного слайда?
> 
> Меняю его с помощью css, у активного слайда есть класс .splide__slide.is-active

Тогда тебе придется немного похакать DOM. Внутри слайда ты можешь "пойти вверх" по нодам и узнать, есть ли у родителя класс `.splide__slide.is-active`. Если есть - значит слайд активный и ты можешь показать описание.

Пример кода, который ищет у всех предков ноды свойство `overflow: hidden`

<details>

```javascript
let parent = document.querySelector('.sticky').parentElement;

while (parent) {
    const hasOverflow = getComputedStyle(parent).overflow;
    if (hasOverflow !== 'visible') {
        console.log(hasOverflow, parent);
    }
    parent = parent.parentElement;
}
```

</details>

**Comment by brusselboy** [comment]
> > > А как ты тогда меняешь размер у активного слайда?
> > 
> > 
> > Меняю его с помощью css, у активного слайда есть класс .splide__slide.is-active
> 
> Тогда тебе придется немного похакать DOM. Внутри слайда ты можешь "пойти вверх" по нодам и узнать, есть ли у родителя класс `.splide__slide.is-active`. Если есть - значит слайд активный и ты можешь показать описание.
> 
> Пример кода, который ищет у всех предков ноды свойство `overflow` не равное `visible`

Родитель .splide__slide, у него через цикл как я понял надо смотреть есть ли .splide__slide.is-active, не совсем понимаю как это нужно проверять

```js

 if (typeof window === 'object') {
    let parent = document.querySelector('.splide__slide');

    while (parent) {
      const hasIsActive = document.querySelector('.splide__slide.is-active');
      if (hasIsActive) {
        console.log(hasIsActive, parent);
      }
      parent = parent.parentElement;
    }
  }

```

**Comment by brusselboy** [comment]
## Алгоритм проверки className у родителя
@TFK70 
1. Берём родителя .splide__slide
2. У него проверяем есть ли класс .splide__slide.is-active
Думаю можно было бы использовать для этого метод contains, выглядело бы это как-то так:

``` js
const result = parent.contains(child); 
```

где parent .splide__slide, а child .splide__slide.is-active. Но есть одна проблема, что у слайдера есть clone слайды у которых тоже есть класс is-active:
```html
<li class="splide__slide splide__slide--clone is-active is-visible" id="splide01-clone01"></li>
```
и на данный момент при проверке на наличие is-active класса, она выдаёт все клоны слайдов, а не нужный нам активный слайд

**Comment by TFK70** [comment]
@brusselboy проверь пожалуйста текущее состояние [этого](https://github.com/torin-asakura/shinny-dvor/pull/11) пра и пометь комменты которые все еще актуальны на твой взгляд

В любом случае отпишись что тебе осталось закончить по слайдеру, т.к. судя по прогрессу это единственное, что осталось сделать

**Comment by brusselboy** [comment]
> @brusselboy проверь пожалуйста текущее состояние [этого](https://github.com/torin-asakura/shinny-dvor/pull/11) пра и пометь комменты которые все еще актуальны на твой взгляд
> 
> В любом случае отпишись что тебе осталось закончить по слайдеру, т.к. судя по прогрессу это единственное, что осталось сделать

@TFK70 

#### Что доделано:

1. К инфографике ([колесо ](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=315%3A115)на главной странице) добавлены подсказки и для пк и для мобилок.
2. Пофикшены все чеки
3. Добавлен [drawer](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=355%3A4691) в хедере для мобильной версии.
4. Пофикшены проблемы с версткой
5. Исправлен [данный](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=347%3A1080) селект, не было возможности выбрать несколько айтемов. Так же исправлены стили.

#### Осталось доделать:
1. Слайдер (скрытие доп. описания у неактивных слайдов)
2. Адаптировать под мобильные устройства

**Comment by brusselboy** [comment]
> От меня что-то требуется? Помощь и т.п.?

@TFK70 пока-что нет

**Comment by TFK70** [comment]
https://github.com/torin-asakura/shinny-dvor/pull/6
